### PR TITLE
Add 2.13.4 support

### PR DESCRIPTION
**Pull request by ckipp01**
Just pr adds in support for 2.13.4 which we would like to include in our Metals release that supports 2.13.4.

### CODE REVIEW

**Comment by alexarchambault** [comment]
Just pushed an extra commit that will (hopefully) address the compilation errors. (That's because some conversions were marked as non explicit in `2.13.4`, look for `CharSequence` in the [`2.13.4` release notes](https://github.com/scala/scala/releases/tag/v2.13.4).)

**Comment by ckipp01** [comment]
> Just pushed an extra commit that will (hopefully) address the compilation errors. (That's because some conversions were marked as non implicit in `2.13.4`, look for `CharSequence` in the [`2.13.4` release notes](https://github.com/scala/scala/releases/tag/v2.13.4).)

Hey! Thanks for taking a peak! I just threw this up here this morning before work hoping for the best 😬 , but I had planned on taking a look back after work. It looks like it's still failing, so if you do want to keep working on it, by all means please do! If not I'll try to take a look tonight at what's going on.

**Comment by alexarchambault** [comment]
@ckipp01 Feel free to have a look later on. I'm not sure I'll be able to have a look today.

**Comment by ckipp01** [comment]
So I don't really get what's going on here and why the changes are affecting those tests...

**Pull request closed without merging**
