### PR TITLE
add beforeExitHooks for cleanup before repl exits

### PR DESCRIPTION
**Pull request by emanresusername**
inspired by #121 but not exactly what we were discussing there
not sure if this is the best (or even a good 😅 ) way to do this
but really just wanted something that worked [like this](https://github.com/emanresusername/.ammonite/blob/akkators/predef.sc#L112-L125) and this handled that usecase well enough for me :)

glad to hear other thoughts/suggestions/improvements/etc

### CODE REVIEW

**Comment by deusaquilus** [comment]
I'm also seeing issues in the Travis Scala 2.10.6 build and I don't understand the error at all. Maybe this build is flaky?

**Comment by emanresusername** [comment]
yeah, i was getting something about a `class.bak` file somewhere not being found, pretty sure it's not related to the code changes here @lihaoyi any ideas?

**Comment by lihaoyi** [comment]
Yeah that's just a flake; we can ignore it, unless you want to dig into why it's happening (I haven't had the time to)

**Comment by lihaoyi** [comment]
Looks good to me

**Pull request merged**
