### PR TITLE
Pass unmodified arguments to the interpreter

### PR DESCRIPTION
**Pull request by suiryc**
As requested in #538 and attempted in #440, here is a commit to pass non-ammonite arguments to the interpreter, available as `interp.args` once amm is launched.

Comes with a unit test to have more chances to land ;)

### CODE REVIEW

**Comment by suiryc** [comment]
Also added an integration test.
Now both the interpreter and the script execution are tested for those arguments.

**Comment by lihaoyi** [comment]
I see this, but won't have time to look at it for a few days I think. I'll need to properly page in all my Ammonite-internals related data into my head so I can properly compare it with #539 and decide what to do. Might need to wait until the weekend

**Comment by suiryc** [comment]
Fair enough.

My intention was more like keeping separate the usage of `@main` entry points (which may be multiple and for which ammonite use its own argument parsing) and the possible usage of `interp.args` when a CLI parser like scopt is used in the script (and thus where no entry point would be needed/used).

Having the script file being the separator between ammonite and the script args as proposed in #479 would have been nice. But since scopt does not seem to expose the options (at least names) that were used to build its parser it would be less elegant when looking for where is actually the script file in the CLI arguments.
Anyway, looking forward being able to run `amm` and use scopt inside the script, with e.g. a shebang like
```
#!/bin/bash
exec amm "$0" -- "$@"
!#
```
(and possibly the `--no-arg-parse` to make sure script arguments are not parsed at all)

**Comment by jtcwang** [comment]
Thanks for this. For scripts to accept arbitrary arguments we do need the `--no-arg-parse` PR merged first. Currently I'm stuck on setting up tests for that PR (since ATM there are no integration tests involving making sure that Ammonite arguments e.g. `-s` are parsed correctly)

**Comment by lihaoyi** [comment]
Superseded by https://github.com/lihaoyi/Ammonite/commit/c605d8600c9749b13ade1f85aa6250f959a0a7ff

**Pull request closed without merging**
