### PR TITLE
For Range Pretty Print

### PR DESCRIPTION
**Pull request by Saheb**
Previously
```
@ 1 to 10
res3: collection.immutable.Range.Inclusive = Range(1, 2, 3, 4, 5, 6, 7, 8, 9, 10)
```

By this change
```
@ 1 to 10
res4: Range.Inclusive = Range(1, 2, 3, 4, 5, 6, 7, 8, 9, 10)
```

### CODE REVIEW

**Comment by lihaoyi** [comment]
@Saheb can you describe briefly, in english, what this change does and why it fixes what it seems to fix?

**Comment by Saheb** [comment]
@lihaoyi - I am new to refelction, was just playing around with symbols and types, and while tweeking, got this to work. Not sure with the resoning behind it. Trying to figure it out.

**Comment by lihaoyi** [comment]
Well let me know if you figure something out. It would be nice to know kinda-sorta why this works before merging it. Also, would be nice to have a unit test because CI is cheap and I'm not paying for it

I hear @paulp knows about the scala refelction API but he may be busy

image

**Comment by lihaoyi** [comment]
Also, if you're fast, this can go out with #338 and the "fix" for #199 in the next release

**Pull request merged**
