### PR TITLE
Java 7 compatibility

### PR DESCRIPTION
**Pull request by alexarchambault**
Would you be ok to be compatible with Java 7? Some people (me included) still have some machines around with it. The changes required are minor.

### CODE REVIEW

**Comment by lihaoyi** [comment]
Looks good to me. I'm running Java 8 though, so will likely end up breaking things in future accidentally, unless you have CI or something set up

**Comment by alexarchambault** [comment]
Here it is:
https://github.com/lihaoyi/Ammonite/pull/30

**Comment by Kwestor** [comment]
Setting up a Travis build for both 7 and 8 should be trivial.

You do use sbt, so something like this should suffice:

```yaml
language: scala
scala:
  - "2.11.6"
jdk:
  - openjdk7
  - oraclejdk8
```

**Comment by lihaoyi** [comment]
Ok merges the travis CI stuff. Anything else I need to do?

**Comment by Kwestor** [comment]
Yep, go https://travis-ci.org/lihaoyi/Ammonite, log with GitHub and add Ammonite to your builds.

**Comment by lihaoyi** [comment]
Ok, i flipped a switch that looks like it does what we want
screenshot 2015-03-06 19 00 01

**Comment by alexarchambault** [comment]
Yep, these were the right things to do.

**Comment by alexarchambault** [comment]
Actually, you should have done them *before* merging for a build to be launched automatically. I think you should be able to launch one manually though.

**Pull request merged**
