### PR TITLE
2.13.0-M5

### PR DESCRIPTION
**Pull request by alexarchambault**
Blocked by
- [x] [fansi](https://github.com/lihaoyi/fansi) (https://github.com/lihaoyi/fansi/pull/19, needs release)
- [x] [upickle](https://github.com/lihaoyi/upickle) (https://github.com/lihaoyi/upickle/pull/267)
- [x] [PPrint](https://github.com/lihaoyi/PPrint) (https://github.com/lihaoyi/PPrint/pull/27)
- [x] [os-lib](https://github.com/lihaoyi/os-lib) (https://github.com/lihaoyi/os-lib/pull/21)
- [x] [requests](https://github.com/lihaoyi/requests-scala) (https://github.com/lihaoyi/requests-scala/pull/34)

### CODE REVIEW

**Comment by alexarchambault** [comment]
(Re-opens https://github.com/lihaoyi/Ammonite/pull/871, that I closed by mistake by deleting its branch.)

**Comment by alexarchambault** [comment]
@lihaoyi In case you didn't notice, the support for `2.13.0-M5` in the remaining libs needed some adjustments, hence the PRs above (that I don't have the rights to merge, but even if I had, I guess a small review would be better).

**Comment by lihaoyi** [comment]
@alexarchambault I went and merged everything, looks fine I guess

**Comment by lihaoyi** [comment]
Feel free to re-publish

**Comment by alexarchambault** [comment]
So my attempts at publishing upickle resulted in two borked releases of it :| (`0.7.2` and `0.7.3`). I'm getting [this error](https://gist.github.com/alexarchambault/34b1215839d0e468d4b3bda0a2947b79). I'm running `mill '__.publish'` from the upickle sources, adjusting `publishVersion` in `build.sc` before, and passing `--sonatypeCreds …`, `--release true`, `--gpgPassphrase …` to mill too. (I though my first attempt failed because of a flaky connection, but I got the same error on a more reliable one…)

I may try again next week, publishing the scala versions one-by-one this time. Feel free to take over if you want to, @lihaoyi.

**Comment by lihaoyi** [comment]
@alexarchambault normally when I see that error it means Sonatype's flaky infrastructure is blowing up and trying again later usually works

**Comment by alexarchambault** [comment]
I guess I'll try tomorrow then (Saturday), the Sonatype servers should be less busy.

**Comment by lihaoyi** [comment]
Travis CI has also been having problems https://www.reddit.com/r/programming/comments/b6l559/travisci_has_been_down_for_over_24_hours/

**Comment by alexarchambault** [comment]
So everything's published (releases go unbelievably smooth on Saturday mornings European time…). Just got to have things compile and tests pass here now.

**Comment by lihaoyi** [comment]
@alexarchambault should we close this then?

**Comment by alexarchambault** [comment]
Not yet. All of Ammonite dependencies are cross-built and published, but not Ammonite itself yet. I'll update this branch with the changes that are needed in Ammonite.

**Comment by alexarchambault** [comment]
@lihaoyi Are you ok if I (or anyone) setup Travis CI stages to publish things from the CI for the projects above (fansi and all)?

This would only require you to add a few variables in the Travis CI settings (the same as [here](https://github.com/olafurpg/sbt-ci-release/#travis)). A `gpg --import` and the right `mill __.publish` should be enough to publish things from Travis then.

cc @olafurpg

**Comment by alexarchambault** [comment]
Kind of like [Ammonite itself](https://github.com/lihaoyi/Ammonite/blob/00a8cbc623095a9e750620e95b4c723df79fd920/build.sc#L472) actually…

**Pull request closed without merging**
