### PR TITLE
Upgrade to Scala 2.12.11

### PR DESCRIPTION
**Pull request by alexarchambault**
Supersedes https://github.com/lihaoyi/Ammonite/pull/1041.

### CODE REVIEW

**Comment by alexarchambault** [comment]
@lihaoyi It seems there are gpg-related errors on the CI during publishing:
```
gpg: no valid OpenPGP data found.
gpg: Total number processed: 0
1 targets failed
publishSonatype ammonite.ops.InteractiveShelloutException
    ammonite.ops.Shellout$.executeInteractive(Shellout.scala:56)
    ammonite.ops.Shellout$.$anonfun$$percent$1(Shellout.scala:14)
    ammonite.ops.Shellout$.$anonfun$$percent$1$adapted(Shellout.scala:14)
    ammonite.ops.Command.applyDynamic(Shellout.scala:118)
    ammonite.$file.build.$anonfun$publishSonatype$4(build.sc:690)
    scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
```
Did anything change around gpg or its settings recently?

**Comment by lihaoyi** [comment]
@alexarchambault I think I rotated my GPG key some time ago (lost the original in an unfortunate `rm -rf` accident), I can try putting the new one into travis CI

**Comment by lihaoyi** [comment]
This must have been months ago though, did it start failing recently?

**Comment by alexarchambault** [comment]
[This one](https://travis-ci.org/github/lihaoyi/Ammonite/builds/636697633) was fine on the 2020/01/14. [This one](https://travis-ci.org/github/lihaoyi/Ammonite/builds/666350192) on the 2020/03/24 isn't.

It seems no master build went up to the release jobs between those.

**Comment by lihaoyi** [comment]
@alexarchambault I tried updated the `SONATYPE_PGP_KEY_CONTENTS` with the output of `gpg --armor --export-secret-keys` on my local machine; could you kick off another build and see if it works?

**Comment by lihaoyi** [comment]
I think `SONATYPE_PGP_PASSWORD` should be unchanged, and as far as I can tell `SONATYPE_PGP_PUB_KEY_CONTENTS` isn't used anywhere

**Comment by alexarchambault** [comment]
@lihaoyi Seems [it's still failing](https://travis-ci.org/github/lihaoyi/Ammonite/jobs/672774560).

You may want to try with the GPG / Travis settings instructions of @olafurpg's [sbt-ci-release](https://github.com/olafurpg/sbt-ci-release), up to the creation of the `SONATYPE_USERNAME` / `SONATYPE_PASSWORD`, `PGP_PASSPHRASE` / `PGP_SECRET` settings on Travis CI. These are independent of sbt, and plenty of people have been following them fine. I used to publish with mill in [this repository](https://github.com/coursier/apps) based on that. Running [these commands](https://github.com/coursier/apps/blob/5b2725578c5ee219d6205830529a7a8efc2cdced/.travis.yml#L17-L18) from Travis CI to publish with mill worked for me.

**Pull request merged**
