### PR TITLE
Show newly available packages when loading dependencies, addresses #245

### PR DESCRIPTION
**Pull request by Grogs**
Addresses #245. Manually tested, raising PR to see which tests it breaks.

Limitation: Only works for dependencies loaded via `interp.load.ivy`. Imports via `import $ivy....` don't display the output. Not sure why, I haven't looked into the mechanics of how $ivy differs from interp.load.

Example output:

```
@ interp.load.ivy("org.scalaj" %% "scalaj-http" % "2.2.0")
Loaded scalaj-http_2.11 2.2.0, with packages: scalaj.http
```

```
@ interp.load.ivy("org.typelevel" %% "cats-core" % "0.8.0")
Loaded cats-core_2.11 0.8.0, with packages: cats.syntax, cats.data, cats, cats.arrow, cats.instances, cats.functor
```

### CODE REVIEW

**Comment by Grogs** [comment]
Updated to handle 'import $ivy...` in the same way; print newly loaded packages if verbose is true.

```
@ interp.load.ivy("com.lihaoyi" %% "fansi" % "0.2.3")
Loaded fansi_2.11 0.2.3, with packages: fansi
```

```
@ import $ivy.`com.lihaoyi::scalatags:0.6.1`
Loaded scalatags_2.11 0.6.1, with packages: scalatags.generic, scalatags.stylesheet, scalatags, scalatags.text
```

**Comment by Grogs** [comment]
Now it's printing this on `import $ivy` it's putting output in my scripts, which I don't like. And I can't turn it off unless I switch to interp.load.ivy.

Ideally I'd like a flag which tell me if ammonite is running in interactive mode, so this can be printed in the repl, but not scripts.

@lihaoyi, please let me know your thoughts on this change and/or the original feature request. I'll focus on other things if there's no interest in this feature. If it is something that may get merged, I'm happy to look into how to implement a flag to see if we're in interactive mode.

**Comment by lihaoyi** [comment]
I think this is a good idea. I agree with you that we should show it in the REPL and not in scripts.

At first glance it looks to me like the best way to implement a flag would be to pass a `isScript: Boolean` down from `preprocessScript` or `processLine` down into `ImportHook#handle` and from there into `Interpreter#loadIvy`.

At first glance `verbose` isn't quite what we want for this - we're using that to toggle verbosity of things in scripts, whereas this is scripts vs REPL.

As for explicit `load.ivy` method calls, I don't actually know what the ideal thing to do there would be. Maybe hardcode add an extra `showPkgs: Boolean = false` flag and let people pass in `true` if they really care? I don't think `load.ivy` will get used that much overall now that `import $ivy` is available

**Comment by lihaoyi** [comment]
Getting the following trying to run this

```scala
[error] /Users/lihaoyi/Dropbox/Workspace/Ammonite/amm/src/test/scala/ammonite/CachingTests.scala:123: not enough arguments for method ivy: (coordinates: (String, String, String), interactive: Boolean, verbose: Boolean)Unit.
[error] Unspecified value parameter interactive.
[error]       interp.interpApi.load.ivy("com.lihaoyi" %% "scalatags" % "0.6.2")
[error]                                ^
[warn] one warning found
[error] one error found
[error] (amm/test:compileIncremental) Compilation failed
[error] Total time: 34 s, completed 15 Dec, 2016 4:29:22 PM
```

Make sure you rebase/merge onto master and get things building and let me know when I should take a look at this again

**Comment by Grogs** [comment]
Yeah, it's not ready yet, I'll comment when it's ready for another look. I was pushing WIP commits so I could check CI.

**Comment by lihaoyi** [comment]
Closing due to inactivity

**Pull request closed without merging**
