### PR TITLE
avoid loading non-jar from load.ivy's classpath to prevent repl blow-up

### PR DESCRIPTION
**Pull request by hamero**
Dependencies loaded via load.ivy can sometime contains non-jar files (e.g. pom) which blows up the repl, e.g.:

    sbt -Dammonite.trace-classpath=true 'project repl' run

and then

    load.ivy( "org.apache.tuscany.sca" % "tuscany-base-runtime-pom" % "2.0.1")

will results in 
```
ERROR: error while loading <root>, Error accessing /Users/hamero/.ivy2/cache/org.apache.tuscany.sca/tuscany-core-runtime-pom/poms/tuscany-core-runtime-pom-2.0.1.pom
scala.reflect.internal.MissingRequirementError: object java.lang.Object in compiler mirror not found.
	scala.reflect.internal.MissingRequirementError$.signal(MissingRequirementError.scala:17)
	scala.reflect.internal.MissingRequirementError$.notFound(MissingRequirementError.scala:18)
	scala.reflect.internal.Mirrors$RootsBase.getModuleOrClass(Mirrors.scala:53)
	scala.reflect.internal.Mirrors$RootsBase.getModuleOrClass(Mirrors.scala:45)
	scala.reflect.internal.Mirrors$RootsBase.getModuleOrClass(Mirrors.scala:45)
	scala.reflect.internal.Mirrors$RootsBase.getModuleOrClass(Mirrors.scala:66)
	scala.reflect.internal.Mirrors$RootsBase.getClassByName(Mirrors.scala:102)
	scala.reflect.internal.Mirrors$RootsBase.getRequiredClass(Mirrors.scala:105)
	scala.reflect.internal.Definitions$DefinitionsClass.ObjectClass$lzycompute(Definitions.scala:257)
	scala.reflect.internal.Definitions$DefinitionsClass.ObjectClass(Definitions.scala:257)
	scala.reflect.internal.Definitions$DefinitionsClass.init(Definitions.scala:1394)
	scala.tools.nsc.Global$Run.<init>(Global.scala:1215)
	ammonite.repl.interp.Compiler$$anon$4.<init>(Compiler.scala:204)
	ammonite.repl.interp.Compiler$.apply(Compiler.scala:129)
	ammonite.repl.interp.Interpreter.init(Interpreter.scala:329)
	ammonite.repl.interp.Interpreter$DefaultLoadJar.ivy(Interpreter.scala:219)
	cmd2$.<init>(Main.scala:34)
	cmd2$.<clinit>(Main.scala:-1)
```
This PR fixed the issue by filtering out non-jar files before adding to the session classpath.

### CODE REVIEW

**Comment by lihaoyi** [comment]
This seems reasonable. 

Can you write up a paragraph or two about what resolving a non-jar file from ivy means in the first place? I'm relatively ignorant of the details of maven/ivy/poms/resolvers so a quick primer would be very helpful

**Comment by lihaoyi** [comment]
Also CI is complaining about your line length =P

**Comment by lihaoyi** [comment]
bump

**Comment by lihaoyi** [comment]
bump @hamero

**Comment by hamero** [comment]
Hey,

I have no idea how does ivy resolve non-jar dependencies. 

It just happen that I had come across some internal third-party dependency that transitively pulls in non-jar files. I'm guessing this is coming from maven-based project which expose some common project settings as a pom. 

Since the original dependency is not publicly available, the example dependency was the result of a quick trial & error search on http://mvnrepository.com to demo the issue.

**Comment by lihaoyi** [comment]
This seems (?) to be fixed by 0.7.0; at least using `import $ivy` on those coordinates seems to succeed

```
Welcome to the Ammonite Repl 0.7.0
(Scala 2.11.8 Java 1.8.0_25)
@ import $ivy.`org.apache.tuscany.sca:tuscany-base-runtime-pom:2.0.1`
:: loading settings :: url = jar:file:/usr/local/bin/amm!/org/apache/ivy/core/settings/ivysettings.xml
:: resolving dependencies :: org.apache.tuscany.sca#tuscany-base-runtime-pom-caller;working
	confs: [default]
	found org.apache.tuscany.sca#tuscany-base-runtime-pom;2.0.1 in central
	found org.apache.tuscany.sca#tuscany-core-runtime-pom;2.0.1 in central
	found org.apache.tuscany.sca#tuscany-assembly;2.0.1 in central
	found org.apache.tuscany.sca#tuscany-monitor;2.0.1 in central
	found org.apache.tuscany.sca#tuscany-extensibility;2.0.1 in central
	found org.apache.tuscany.sca#tuscany-assembly-xml;2.0.1 in central
	found org.apache.tuscany.sca#tuscany-contribution;2.0.1 in central
	found org.apache.tuscany.sca#tuscany-assembly-xsd;2.0.1 in central
	found org.apache.tuscany.sca#tuscany-common-xml;2.0.1 in central
	found org.apache.tuscany.sca#tuscany-common-java;2.0.1 in central
	found org.apache.tuscany.sca#tuscany-sca-api;2.0.1 in central
	found org.apache.tuscany.sca#tuscany-xsd;2.0.1 in central
	found org.apache.ws.commons.schema#XmlSchema;1.4.3 in central
	found org.apache.tuscany.sca#tuscany-binding-ws;2.0.1 in central
	found org.apache.tuscany.sca#tuscany-interface-wsdl;2.0.1 in central
	found wsdl4j#wsdl4j;1.6.2 in central
	found org.apache.tuscany.sca#tuscany-binding-ws-wsdlgen;2.0.1 in central
	found org.apache.tuscany.sca#tuscany-interface-java;2.0.1 in central
	found org.apache.tuscany.sca#tuscany-interface-java-jaxws;2.0.1 in central
	found org.apache.tuscany.sca#tuscany-core-spi;2.0.1 in central
	found org.apache.tuscany.sca#tuscany-databinding-jaxb;2.0.1 in central
	found org.apache.tuscany.sca#tuscany-databinding;2.0.1 in central
	found asm#asm;3.1 in central
	found org.apache.tuscany.sca#tuscany-builder;2.0.1 in central
	found org.apache.tuscany.sca#tuscany-common-http;2.0.1 in central
	found org.apache.tuscany.sca#tuscany-core;2.0.1 in central
	found cglib#cglib;2.2 in central
	found org.apache.tuscany.sca#tuscany-core-databinding;2.0.1 in central
	found org.apache.tuscany.sca#tuscany-deployment;2.0.1 in central
	found org.apache.tuscany.sca#tuscany-host-http;2.0.1 in central
	found org.apache.tuscany.sca#tuscany-node-api;2.0.1 in central
	found org.apache.tuscany.sca#tuscany-binding-sca-runtime;2.0.1 in central
	found org.apache.tuscany.sca#tuscany-binding-ws-runtime-jaxws-ri;2.0.1 in central
	found org.apache.tuscany.sca#tuscany-binding-ws-runtime-jaxws;2.0.1 in central
	found org.apache.tuscany.sca#tuscany-data-api;2.0.1 in central
	found org.apache.tuscany.sca#tuscany-domain-node;2.0.1 in central
	found org.apache.tuscany.sca#tuscany-node-impl;2.0.1 in central
	found org.apache.tuscany.sca#tuscany-implementation-web-runtime;2.0.1 in central
	found org.apache.tuscany.sca#tuscany-implementation-web;2.0.1 in central
	found org.apache.tuscany.sca#tuscany-implementation-java-runtime;2.0.1 in central
	found org.apache.tuscany.sca#tuscany-implementation-java;2.0.1 in central
	found org.apache.tuscany.sca#tuscany-host-webapp;2.0.1 in central
	found org.apache.tuscany.sca#tuscany-launcher;2.0.1 in central
	found org.apache.tuscany.sca#tuscany-sca-client-impl;2.0.1 in central
	found org.apache.tuscany.sca#tuscany-host-jetty;2.0.1 in central
	found org.apache.tuscany.sca#tuscany-shell;2.0.1 in central
	found org.apache.tuscany.sca#tuscany-wink;2.0.1 in central
	found org.apache.tuscany.sca#tuscany-policy-security;2.0.1 in central
	found org.apache.tuscany.sca#tuscany-binding-atom;2.0.1 in central
	found org.apache.tuscany.sca#tuscany-binding-comet;2.0.1 in central
	found org.apache.tuscany.sca#tuscany-binding-corba;2.0.1 in central
	found org.apache.tuscany.sca#tuscany-host-corba;2.0.1 in central
	found org.apache.tuscany.sca#tuscany-binding-ejb;2.0.1 in central
	found org.apache.tuscany.sca#tuscany-binding-http;2.0.1 in central
	found org.apache.tuscany.sca#tuscany-binding-jms;2.0.1 in central
	found org.apache.tuscany.sca#tuscany-binding-jsonp;2.0.1 in central
	found org.apache.tuscany.sca#tuscany-binding-jsonrpc;2.0.1 in central
	found org.apache.tuscany.sca#tuscany-binding-rest;2.0.1 in central
	found org.apache.tuscany.sca#tuscany-binding-rmi;2.0.1 in central
	found org.apache.tuscany.sca#tuscany-implementation-bpel;2.0.1 in central
	found org.apache.tuscany.sca#tuscany-implementation-jaxrs;2.0.1 in central
	found javax.ws.rs#jsr311-api;1.1.1 in central
	found org.apache.tuscany.sca#tuscany-implementation-python;2.0.1 in central
	found org.apache.tuscany.sca#tuscany-implementation-script;2.0.1 in central
	found org.apache.tuscany.sca#tuscany-implementation-spring;2.0.1 in central
	found org.apache.tuscany.sca#tuscany-implementation-widget;2.0.1 in central
downloading http://repo1.maven.org/maven2/org/apache/tuscany/sca/tuscany-core-runtime-pom/2.0.1/tuscany-core-runtime-pom-2.0.1.pom ...
	[SUCCESSFUL ] org.apache.tuscany.sca#tuscany-core-runtime-pom;2.0.1!tuscany-core-runtime-pom.pom (218ms)
downloading http://repo1.maven.org/maven2/org/apache/tuscany/sca/tuscany-binding-sca-runtime/2.0.1/tuscany-binding-sca-runtime-2.0.1.jar ...
	[SUCCESSFUL ] org.apache.tuscany.sca#tuscany-binding-sca-runtime;2.0.1!tuscany-binding-sca-runtime.jar (222ms)
downloading http://repo1.maven.org/maven2/org/apache/tuscany/sca/tuscany-binding-ws-runtime-jaxws-ri/2.0.1/tuscany-binding-ws-runtime-jaxws-ri-2.0.1.jar ...
	[SUCCESSFUL ] org.apache.tuscany.sca#tuscany-binding-ws-runtime-jaxws-ri;2.0.1!tuscany-binding-ws-runtime-jaxws-ri.jar (221ms)
downloading http://repo1.maven.org/maven2/org/apache/tuscany/sca/tuscany-data-api/2.0.1/tuscany-data-api-2.0.1.jar ...
	[SUCCESSFUL ] org.apache.tuscany.sca#tuscany-data-api;2.0.1!tuscany-data-api.jar (218ms)
downloading http://repo1.maven.org/maven2/org/apache/tuscany/sca/tuscany-domain-node/2.0.1/tuscany-domain-node-2.0.1.jar ...
	[SUCCESSFUL ] org.apache.tuscany.sca#tuscany-domain-node;2.0.1!tuscany-domain-node.jar (222ms)
downloading http://repo1.maven.org/maven2/org/apache/tuscany/sca/tuscany-implementation-web-runtime/2.0.1/tuscany-implementation-web-runtime-2.0.1.jar ...
	[SUCCESSFUL ] org.apache.tuscany.sca#tuscany-implementation-web-runtime;2.0.1!tuscany-implementation-web-runtime.jar (220ms)
downloading http://repo1.maven.org/maven2/org/apache/tuscany/sca/tuscany-launcher/2.0.1/tuscany-launcher-2.0.1.jar ...
	[SUCCESSFUL ] org.apache.tuscany.sca#tuscany-launcher;2.0.1!tuscany-launcher.jar (219ms)
downloading http://repo1.maven.org/maven2/org/apache/tuscany/sca/tuscany-sca-client-impl/2.0.1/tuscany-sca-client-impl-2.0.1.jar ...
	[SUCCESSFUL ] org.apache.tuscany.sca#tuscany-sca-client-impl;2.0.1!tuscany-sca-client-impl.jar (220ms)
downloading http://repo1.maven.org/maven2/org/apache/tuscany/sca/tuscany-host-jetty/2.0.1/tuscany-host-jetty-2.0.1.jar ...
	[SUCCESSFUL ] org.apache.tuscany.sca#tuscany-host-jetty;2.0.1!tuscany-host-jetty.jar (330ms)
downloading http://repo1.maven.org/maven2/org/apache/tuscany/sca/tuscany-shell/2.0.1/tuscany-shell-2.0.1.jar ...
	[SUCCESSFUL ] org.apache.tuscany.sca#tuscany-shell;2.0.1!tuscany-shell.jar (222ms)
downloading http://repo1.maven.org/maven2/org/apache/tuscany/sca/tuscany-wink/2.0.1/tuscany-wink-2.0.1.jar ...
	[SUCCESSFUL ] org.apache.tuscany.sca#tuscany-wink;2.0.1!tuscany-wink.jar (219ms)
downloading http://repo1.maven.org/maven2/org/apache/tuscany/sca/tuscany-policy-security/2.0.1/tuscany-policy-security-2.0.1.jar ...
	[SUCCESSFUL ] org.apache.tuscany.sca#tuscany-policy-security;2.0.1!tuscany-policy-security.jar (224ms)
downloading http://repo1.maven.org/maven2/org/apache/tuscany/sca/tuscany-binding-atom/2.0.1/tuscany-binding-atom-2.0.1.jar ...
	[SUCCESSFUL ] org.apache.tuscany.sca#tuscany-binding-atom;2.0.1!tuscany-binding-atom.jar (222ms)
downloading http://repo1.maven.org/maven2/org/apache/tuscany/sca/tuscany-binding-comet/2.0.1/tuscany-binding-comet-2.0.1.jar ...
	[SUCCESSFUL ] org.apache.tuscany.sca#tuscany-binding-comet;2.0.1!tuscany-binding-comet.jar (219ms)
downloading http://repo1.maven.org/maven2/org/apache/tuscany/sca/tuscany-binding-corba/2.0.1/tuscany-binding-corba-2.0.1.jar ...
	[SUCCESSFUL ] org.apache.tuscany.sca#tuscany-binding-corba;2.0.1!tuscany-binding-corba.jar (219ms)
downloading http://repo1.maven.org/maven2/org/apache/tuscany/sca/tuscany-binding-ejb/2.0.1/tuscany-binding-ejb-2.0.1.jar ...
	[SUCCESSFUL ] org.apache.tuscany.sca#tuscany-binding-ejb;2.0.1!tuscany-binding-ejb.jar (220ms)
downloading http://repo1.maven.org/maven2/org/apache/tuscany/sca/tuscany-binding-http/2.0.1/tuscany-binding-http-2.0.1.jar ...
	[SUCCESSFUL ] org.apache.tuscany.sca#tuscany-binding-http;2.0.1!tuscany-binding-http.jar (219ms)
downloading http://repo1.maven.org/maven2/org/apache/tuscany/sca/tuscany-binding-jms/2.0.1/tuscany-binding-jms-2.0.1.jar ...
	[SUCCESSFUL ] org.apache.tuscany.sca#tuscany-binding-jms;2.0.1!tuscany-binding-jms.jar (2120ms)
downloading http://repo1.maven.org/maven2/org/apache/tuscany/sca/tuscany-binding-jsonp/2.0.1/tuscany-binding-jsonp-2.0.1.jar ...
	[SUCCESSFUL ] org.apache.tuscany.sca#tuscany-binding-jsonp;2.0.1!tuscany-binding-jsonp.jar (220ms)
downloading http://repo1.maven.org/maven2/org/apache/tuscany/sca/tuscany-binding-jsonrpc/2.0.1/tuscany-binding-jsonrpc-2.0.1.jar ...
	[SUCCESSFUL ] org.apache.tuscany.sca#tuscany-binding-jsonrpc;2.0.1!tuscany-binding-jsonrpc.jar (219ms)
downloading http://repo1.maven.org/maven2/org/apache/tuscany/sca/tuscany-binding-rest/2.0.1/tuscany-binding-rest-2.0.1.jar ...
	[SUCCESSFUL ] org.apache.tuscany.sca#tuscany-binding-rest;2.0.1!tuscany-binding-rest.jar (220ms)
downloading http://repo1.maven.org/maven2/org/apache/tuscany/sca/tuscany-binding-rmi/2.0.1/tuscany-binding-rmi-2.0.1.jar ...
	[SUCCESSFUL ] org.apache.tuscany.sca#tuscany-binding-rmi;2.0.1!tuscany-binding-rmi.jar (360ms)
downloading http://repo1.maven.org/maven2/org/apache/tuscany/sca/tuscany-binding-ws/2.0.1/tuscany-binding-ws-2.0.1.jar ...
	[SUCCESSFUL ] org.apache.tuscany.sca#tuscany-binding-ws;2.0.1!tuscany-binding-ws.jar (221ms)
downloading http://repo1.maven.org/maven2/org/apache/tuscany/sca/tuscany-implementation-bpel/2.0.1/tuscany-implementation-bpel-2.0.1.jar ...
	[SUCCESSFUL ] org.apache.tuscany.sca#tuscany-implementation-bpel;2.0.1!tuscany-implementation-bpel.jar (223ms)
downloading http://repo1.maven.org/maven2/org/apache/tuscany/sca/tuscany-implementation-java/2.0.1/tuscany-implementation-java-2.0.1.jar ...
	[SUCCESSFUL ] org.apache.tuscany.sca#tuscany-implementation-java;2.0.1!tuscany-implementation-java.jar (1434ms)
downloading http://repo1.maven.org/maven2/org/apache/tuscany/sca/tuscany-implementation-jaxrs/2.0.1/tuscany-implementation-jaxrs-2.0.1.jar ...
	[SUCCESSFUL ] org.apache.tuscany.sca#tuscany-implementation-jaxrs;2.0.1!tuscany-implementation-jaxrs.jar (222ms)
downloading http://repo1.maven.org/maven2/org/apache/tuscany/sca/tuscany-implementation-python/2.0.1/tuscany-implementation-python-2.0.1.jar ...
	[SUCCESSFUL ] org.apache.tuscany.sca#tuscany-implementation-python;2.0.1!tuscany-implementation-python.jar (354ms)
downloading http://repo1.maven.org/maven2/org/apache/tuscany/sca/tuscany-implementation-script/2.0.1/tuscany-implementation-script-2.0.1.jar ...
	[SUCCESSFUL ] org.apache.tuscany.sca#tuscany-implementation-script;2.0.1!tuscany-implementation-script.jar (408ms)
downloading http://repo1.maven.org/maven2/org/apache/tuscany/sca/tuscany-implementation-spring/2.0.1/tuscany-implementation-spring-2.0.1.jar ...
	[SUCCESSFUL ] org.apache.tuscany.sca#tuscany-implementation-spring;2.0.1!tuscany-implementation-spring.jar (414ms)
downloading http://repo1.maven.org/maven2/org/apache/tuscany/sca/tuscany-implementation-web/2.0.1/tuscany-implementation-web-2.0.1.jar ...
	[SUCCESSFUL ] org.apache.tuscany.sca#tuscany-implementation-web;2.0.1!tuscany-implementation-web.jar (403ms)
downloading http://repo1.maven.org/maven2/org/apache/tuscany/sca/tuscany-implementation-widget/2.0.1/tuscany-implementation-widget-2.0.1.jar ...
	[SUCCESSFUL ] org.apache.tuscany.sca#tuscany-implementation-widget;2.0.1!tuscany-implementation-widget.jar (289ms)
downloading http://repo1.maven.org/maven2/org/apache/tuscany/sca/tuscany-assembly/2.0.1/tuscany-assembly-2.0.1.jar ...
	[SUCCESSFUL ] org.apache.tuscany.sca#tuscany-assembly;2.0.1!tuscany-assembly.jar (1941ms)
downloading http://repo1.maven.org/maven2/org/apache/tuscany/sca/tuscany-assembly-xml/2.0.1/tuscany-assembly-xml-2.0.1.jar ...
	[SUCCESSFUL ] org.apache.tuscany.sca#tuscany-assembly-xml;2.0.1!tuscany-assembly-xml.jar (649ms)
downloading http://repo1.maven.org/maven2/org/apache/tuscany/sca/tuscany-assembly-xsd/2.0.1/tuscany-assembly-xsd-2.0.1.jar ...
	[SUCCESSFUL ] org.apache.tuscany.sca#tuscany-assembly-xsd;2.0.1!tuscany-assembly-xsd.jar (611ms)
downloading http://repo1.maven.org/maven2/org/apache/tuscany/sca/tuscany-binding-ws-wsdlgen/2.0.1/tuscany-binding-ws-wsdlgen-2.0.1.jar ...
	[SUCCESSFUL ] org.apache.tuscany.sca#tuscany-binding-ws-wsdlgen;2.0.1!tuscany-binding-ws-wsdlgen.jar (224ms)
downloading http://repo1.maven.org/maven2/org/apache/tuscany/sca/tuscany-builder/2.0.1/tuscany-builder-2.0.1.jar ...
	[SUCCESSFUL ] org.apache.tuscany.sca#tuscany-builder;2.0.1!tuscany-builder.jar (809ms)
downloading http://repo1.maven.org/maven2/org/apache/tuscany/sca/tuscany-common-java/2.0.1/tuscany-common-java-2.0.1.jar ...
	[SUCCESSFUL ] org.apache.tuscany.sca#tuscany-common-java;2.0.1!tuscany-common-java.jar (220ms)
downloading http://repo1.maven.org/maven2/org/apache/tuscany/sca/tuscany-common-http/2.0.1/tuscany-common-http-2.0.1.jar ...
	[SUCCESSFUL ] org.apache.tuscany.sca#tuscany-common-http;2.0.1!tuscany-common-http.jar (237ms)
downloading http://repo1.maven.org/maven2/org/apache/tuscany/sca/tuscany-common-xml/2.0.1/tuscany-common-xml-2.0.1.jar ...
	[SUCCESSFUL ] org.apache.tuscany.sca#tuscany-common-xml;2.0.1!tuscany-common-xml.jar (539ms)
downloading http://repo1.maven.org/maven2/org/apache/tuscany/sca/tuscany-contribution/2.0.1/tuscany-contribution-2.0.1.jar ...
	[SUCCESSFUL ] org.apache.tuscany.sca#tuscany-contribution;2.0.1!tuscany-contribution.jar (840ms)
downloading http://repo1.maven.org/maven2/org/apache/tuscany/sca/tuscany-core/2.0.1/tuscany-core-2.0.1.jar ...
	[SUCCESSFUL ] org.apache.tuscany.sca#tuscany-core;2.0.1!tuscany-core.jar (1048ms)
downloading http://repo1.maven.org/maven2/org/apache/tuscany/sca/tuscany-core-databinding/2.0.1/tuscany-core-databinding-2.0.1.jar ...
	[SUCCESSFUL ] org.apache.tuscany.sca#tuscany-core-databinding;2.0.1!tuscany-core-databinding.jar (227ms)
downloading http://repo1.maven.org/maven2/org/apache/tuscany/sca/tuscany-core-spi/2.0.1/tuscany-core-spi-2.0.1.jar ...
	[SUCCESSFUL ] org.apache.tuscany.sca#tuscany-core-spi;2.0.1!tuscany-core-spi.jar (749ms)
downloading http://repo1.maven.org/maven2/org/apache/tuscany/sca/tuscany-databinding/2.0.1/tuscany-databinding-2.0.1.jar ...
	[SUCCESSFUL ] org.apache.tuscany.sca#tuscany-databinding;2.0.1!tuscany-databinding.jar (656ms)
downloading http://repo1.maven.org/maven2/org/apache/tuscany/sca/tuscany-databinding-jaxb/2.0.1/tuscany-databinding-jaxb-2.0.1.jar ...
	[SUCCESSFUL ] org.apache.tuscany.sca#tuscany-databinding-jaxb;2.0.1!tuscany-databinding-jaxb.jar (539ms)
downloading http://repo1.maven.org/maven2/org/apache/tuscany/sca/tuscany-deployment/2.0.1/tuscany-deployment-2.0.1.jar ...
	[SUCCESSFUL ] org.apache.tuscany.sca#tuscany-deployment;2.0.1!tuscany-deployment.jar (221ms)
downloading http://repo1.maven.org/maven2/org/apache/tuscany/sca/tuscany-extensibility/2.0.1/tuscany-extensibility-2.0.1.jar ...
	[SUCCESSFUL ] org.apache.tuscany.sca#tuscany-extensibility;2.0.1!tuscany-extensibility.jar (437ms)
downloading http://repo1.maven.org/maven2/org/apache/tuscany/sca/tuscany-host-http/2.0.1/tuscany-host-http-2.0.1.jar ...
	[SUCCESSFUL ] org.apache.tuscany.sca#tuscany-host-http;2.0.1!tuscany-host-http.jar (220ms)
downloading http://repo1.maven.org/maven2/org/apache/tuscany/sca/tuscany-interface-java/2.0.1/tuscany-interface-java-2.0.1.jar ...
	[SUCCESSFUL ] org.apache.tuscany.sca#tuscany-interface-java;2.0.1!tuscany-interface-java.jar (433ms)
downloading http://repo1.maven.org/maven2/org/apache/tuscany/sca/tuscany-interface-java-jaxws/2.0.1/tuscany-interface-java-jaxws-2.0.1.jar ...
	[SUCCESSFUL ] org.apache.tuscany.sca#tuscany-interface-java-jaxws;2.0.1!tuscany-interface-java-jaxws.jar (443ms)
downloading http://repo1.maven.org/maven2/org/apache/tuscany/sca/tuscany-interface-wsdl/2.0.1/tuscany-interface-wsdl-2.0.1.jar ...
	[SUCCESSFUL ] org.apache.tuscany.sca#tuscany-interface-wsdl;2.0.1!tuscany-interface-wsdl.jar (447ms)
downloading http://repo1.maven.org/maven2/org/apache/tuscany/sca/tuscany-monitor/2.0.1/tuscany-monitor-2.0.1.jar ...
	[SUCCESSFUL ] org.apache.tuscany.sca#tuscany-monitor;2.0.1!tuscany-monitor.jar (219ms)
downloading http://repo1.maven.org/maven2/org/apache/tuscany/sca/tuscany-node-api/2.0.1/tuscany-node-api-2.0.1.jar ...
	[SUCCESSFUL ] org.apache.tuscany.sca#tuscany-node-api;2.0.1!tuscany-node-api.jar (269ms)
downloading http://repo1.maven.org/maven2/org/apache/tuscany/sca/tuscany-sca-api/2.0.1/tuscany-sca-api-2.0.1.jar ...
	[SUCCESSFUL ] org.apache.tuscany.sca#tuscany-sca-api;2.0.1!tuscany-sca-api.jar (223ms)
downloading http://repo1.maven.org/maven2/org/apache/tuscany/sca/tuscany-xsd/2.0.1/tuscany-xsd-2.0.1.jar ...
	[SUCCESSFUL ] org.apache.tuscany.sca#tuscany-xsd;2.0.1!tuscany-xsd.jar (389ms)
downloading http://repo1.maven.org/maven2/org/apache/ws/commons/schema/XmlSchema/1.4.3/XmlSchema-1.4.3.jar ...
	[SUCCESSFUL ] org.apache.ws.commons.schema#XmlSchema;1.4.3!XmlSchema.jar (650ms)
downloading http://repo1.maven.org/maven2/wsdl4j/wsdl4j/1.6.2/wsdl4j-1.6.2.jar ...
	[SUCCESSFUL ] wsdl4j#wsdl4j;1.6.2!wsdl4j.jar (650ms)
downloading http://repo1.maven.org/maven2/cglib/cglib/2.2/cglib-2.2.jar ...
	[SUCCESSFUL ] cglib#cglib;2.2!cglib.jar (992ms)
downloading http://repo1.maven.org/maven2/org/apache/tuscany/sca/tuscany-binding-ws-runtime-jaxws/2.0.1/tuscany-binding-ws-runtime-jaxws-2.0.1.jar ...
	[SUCCESSFUL ] org.apache.tuscany.sca#tuscany-binding-ws-runtime-jaxws;2.0.1!tuscany-binding-ws-runtime-jaxws.jar (359ms)
downloading http://repo1.maven.org/maven2/org/apache/tuscany/sca/tuscany-node-impl/2.0.1/tuscany-node-impl-2.0.1.jar ...
	[SUCCESSFUL ] org.apache.tuscany.sca#tuscany-node-impl;2.0.1!tuscany-node-impl.jar (221ms)
downloading http://repo1.maven.org/maven2/org/apache/tuscany/sca/tuscany-implementation-java-runtime/2.0.1/tuscany-implementation-java-runtime-2.0.1.jar ...
	[SUCCESSFUL ] org.apache.tuscany.sca#tuscany-implementation-java-runtime;2.0.1!tuscany-implementation-java-runtime.jar (448ms)
downloading http://repo1.maven.org/maven2/org/apache/tuscany/sca/tuscany-host-webapp/2.0.1/tuscany-host-webapp-2.0.1.jar ...
	[SUCCESSFUL ] org.apache.tuscany.sca#tuscany-host-webapp;2.0.1!tuscany-host-webapp.jar (353ms)
downloading http://repo1.maven.org/maven2/org/apache/tuscany/sca/tuscany-host-corba/2.0.1/tuscany-host-corba-2.0.1.jar ...
	[SUCCESSFUL ] org.apache.tuscany.sca#tuscany-host-corba;2.0.1!tuscany-host-corba.jar (218ms)
import $ivy.$
@
```

I honestly don't know what changed between then and now, but if this is still causing problems feel free to rebase this on master, add a test, and I'll merge it

**Pull request closed without merging**
