### PR TITLE
Remove unnecessary Ivy cache

### PR DESCRIPTION
**Pull request by alexarchambault**
Fixes https://github.com/lihaoyi/Ammonite/issues/874.

### CODE REVIEW

**Comment by lihaoyi** [comment]
This seems like a pretty major change. Are we sure that the coursier cache is as fast as the Ammonite caches in the case where the artifacts are already resolved and downloaded?

**Comment by lihaoyi** [comment]
If so, then I'm fine with it

**Comment by alexarchambault** [comment]
On a warm JVM, even big resolutions take a fraction of a second, e.g. 40 spark-sql resolutions in a row:
```
$ ./coursier fetch org.apache.spark:spark-sql_2.11:2.3.2 -B -40
Warm-up 1 / 40
Resolution 1 / 40: 1472 ms
Warm-up 2 / 40
Resolution 2 / 40: 630 ms
Warm-up 3 / 40
Resolution 3 / 40: 520 ms
Warm-up 4 / 40
Resolution 4 / 40: 457 ms
Warm-up 5 / 40
Resolution 5 / 40: 408 ms
Warm-up 6 / 40
Resolution 6 / 40: 380 ms
Warm-up 7 / 40
Resolution 7 / 40: 387 ms
Warm-up 8 / 40
Resolution 8 / 40: 365 ms
Warm-up 9 / 40
Resolution 9 / 40: 354 ms
Warm-up 10 / 40
Resolution 10 / 40: 328 ms
Warm-up 11 / 40
Resolution 11 / 40: 353 ms
Warm-up 12 / 40
Resolution 12 / 40: 347 ms
Warm-up 13 / 40
Resolution 13 / 40: 323 ms
Warm-up 14 / 40
Resolution 14 / 40: 345 ms
Warm-up 15 / 40
Resolution 15 / 40: 357 ms
Warm-up 16 / 40
Resolution 16 / 40: 323 ms
Warm-up 17 / 40
Resolution 17 / 40: 344 ms
Warm-up 18 / 40
Resolution 18 / 40: 324 ms
Warm-up 19 / 40
Resolution 19 / 40: 324 ms
Warm-up 20 / 40
Resolution 20 / 40: 316 ms
Warm-up 21 / 40
Resolution 21 / 40: 317 ms
Warm-up 22 / 40
Resolution 22 / 40: 328 ms
Warm-up 23 / 40
Resolution 23 / 40: 356 ms
Warm-up 24 / 40
Resolution 24 / 40: 317 ms
Warm-up 25 / 40
Resolution 25 / 40: 321 ms
Warm-up 26 / 40
Resolution 26 / 40: 331 ms
Warm-up 27 / 40
Resolution 27 / 40: 387 ms
Warm-up 28 / 40
Resolution 28 / 40: 381 ms
Warm-up 29 / 40
Resolution 29 / 40: 438 ms
Warm-up 30 / 40
Resolution 30 / 40: 382 ms
Warm-up 31 / 40
Resolution 31 / 40: 430 ms
Warm-up 32 / 40
Resolution 32 / 40: 314 ms
Warm-up 33 / 40
Resolution 33 / 40: 320 ms
Warm-up 34 / 40
Resolution 34 / 40: 331 ms
Warm-up 35 / 40
Resolution 35 / 40: 309 ms
Warm-up 36 / 40
Resolution 36 / 40: 310 ms
Warm-up 37 / 40
Resolution 37 / 40: 316 ms
Warm-up 38 / 40
Resolution 38 / 40: 297 ms
Warm-up 39 / 40
Resolution 39 / 40: 353 ms
Warm-up 40 / 40
Resolution 40 / 40: 308 ms
Benchmark resolution
Resolution 41 / 40: 308 ms
[...]
```

The issues that can arise because of the extra cache layer aren't really worth it I think. It's just my opinion...

**Comment by alexarchambault** [comment]
Superseded by https://github.com/lihaoyi/Ammonite/pull/896.

**Pull request closed without merging**
