### PR TITLE
update to coursier RC8

### PR DESCRIPTION
**Pull request by emanresusername**
[for somewhat selfish reasons :sweat_smile:](https://github.com/coursier/coursier/issues/602)

### CODE REVIEW

**Comment by lihaoyi** [comment]
Looks fine to me I guess, if CI passes I'll merge it and you can use the unstable version

**Comment by lihaoyi** [comment]
CI seems mad; want to take a look?

**Comment by alexarchambault** [comment]
Ok, sorry, looks like this version of coursier is still borked when used via its API 😓

**Comment by alexarchambault** [comment]
coursier `1.0.0-RC8` is out (and seems fine, locally).

**Comment by lihaoyi** [comment]
Green build is good enough for me

**Pull request merged**
