### PR TITLE
SBT plugin

### PR DESCRIPTION
**Pull request by alexarchambault**
Use it by adding
```scala
addSbtPlugin("com.lihaoyi" %% "ammonite-sbt" % "0.2.4")
```
to `project/plugins.sbt` or globally in `~/.sbt/0.13/plugins/build.sbt`.

At the sbt prompt of a sbt project, type `repl` and an Ammonite repl with the project dependencies and build products in the classpath will be launched.

Requires sbt >= 0.13.5 (for auto plugins).

### CODE REVIEW

**Comment by lihaoyi** [comment]
Question: What's the advantage of this over the current "add me to project" snippet? It seems like a whole lot of code that mostly does the same thing, and only really seems to save 1 LOC in a user's project if i'm not mistaken

**Comment by zarthross** [comment]
Seems to me that this would allow a person to easily add this to their global sbt config so it will affect all projects.  I think it is also a bit more idiomatic SBT.

**Comment by alexarchambault** [comment]
Same as @zarthross, you set up ammonite once and it's available in all your projects straight away. It's the same for updates: you have to change the version in one place, and you're done for all your projects.

You can also forget about the details of the one line to add in each project. You just have to remember to type `repl` at the sbt prompt, nothing more.

**Comment by nightscape** [comment]
:+1:
@lihaoyi, do you see any problems with this?
I would really love to add Ammonite-REPL to my global plugins so that I can use it in all projects without hassle.

**Comment by dwijnand** [comment]
:+1: Not only does this work well as a global plugin but I think I also agree with it's standalone config instead of using test.

**Comment by alexarchambault** [comment]
The standalone project is here: https://github.com/alexarchambault/sbt-ammonite.

For now, it uses my cross-published version of Ammonite (https://github.com/alexarchambault/Ammonite), to tackle https://github.com/lihaoyi/Ammonite/issues/15.

**Comment by alexarchambault** [comment]
Closing this as there's now https://github.com/alexarchambault/sbt-ammonite.

**Pull request closed without merging**
