### PR TITLE
Adds fix for #257

### PR DESCRIPTION
**Pull request by edwardsmatt**
* Adds Try to Pressy.scala to catch NPE thrown at Line 68.
* Adds test to AutocompleteTests
* The Failure case simply returns an empty Seq.

### CODE REVIEW

**Comment by lihaoyi** [comment]
failure looks legit

**Comment by lihaoyi** [comment]
at least a few of them do anyway

**Comment by edwardsmatt** [comment]
Yeah, there were a number of tests failing before I forked the code. So I assume the failures were those same tests. The test I added (defTab) was passing, so I that was good enough for me to open the PR :)

**Comment by lihaoyi** [comment]
Lemme stabilize trunk first and i'll take another look at this after

**Comment by edwardsmatt** [comment]
Yep no worries, that makes sense :+1:

**Comment by lihaoyi** [comment]
Almost... just 2.10 is still red. Come one build...

**Comment by lihaoyi** [comment]
Master is green, rebase away!

**Comment by edwardsmatt** [comment]
Hmmm... it appears the tests are failing for Scala 2.10.x. I would have to put a bit more thought into this one. Can you let me know your memory settings for running the entire suite? I keep getting GC OOM errors.

**Comment by lihaoyi** [comment]
I don't have any special settings, all you see in the repo is what I run with, same with the build on travis...

**Comment by edwardsmatt** [comment]
oh cool... no probs... I'll let you know how I go (sorry for all the spam!)

**Comment by edwardsmatt** [comment]
Okay, so I've fixed the broken scala 2.10.x tests :+1: All Green. Thanks for your patience

**Comment by lihaoyi** [comment]
Looks good, thanks!

**Comment by lihaoyi** [comment]
Looks like this didn't actually fix it

```scala
haoyi-haoyi@ defException in thread "main" java.lang.NullPointerException
	at scala.reflect.internal.Definitions$DefinitionsClass.isByNameParamType(Definitions.scala:379)
	at scala.reflect.internal.TreeInfo.isStableIdent(TreeInfo.scala:130)
	at scala.reflect.internal.TreeInfo.isStableIdentifier(TreeInfo.scala:105)
	at scala.reflect.internal.TreeInfo.isPath(TreeInfo.scala:95)
	at scala.reflect.internal.TreeInfo.admitsTypeSelection(TreeInfo.scala:147)
	at scala.tools.nsc.interactive.Global.stabilizedType(Global.scala:961)
	at scala.tools.nsc.interactive.Global.typedTreeAt(Global.scala:810)
	at scala.tools.nsc.interactive.Global$$anonfun$getTypedTreeAt$1.apply(Global.scala:840)
	at scala.tools.nsc.interactive.Global$$anonfun$getTypedTreeAt$1.apply(Global.scala:840)
	at scala.tools.nsc.interactive.Global$$anonfun$respond$1.apply(Global.scala:699)
	at scala.tools.nsc.interactive.Global$$anonfun$respond$1.apply(Global.scala:699)
	at scala.tools.nsc.interactive.Global.respondGradually(Global.scala:706)
	at scala.tools.nsc.interactive.Global.respond(Global.scala:699)
	at scala.tools.nsc.interactive.Global.getTypedTreeAt(Global.scala:840)
	at scala.tools.nsc.interactive.CompilerControl$AskTypeAtItem.apply$mcV$sp(CompilerControl.scala:326)
	at scala.tools.nsc.interactive.Global$$anonfun$pollForWork$1.apply$mcV$sp(Global.scala:504)
	at scala.util.control.Breaks.breakable(Breaks.scala:38)
	at scala.tools.nsc.interactive.Global.pollForWork(Global.scala:429)
	at scala.tools.nsc.interactive.Global.checkForMoreWork(Global.scala:518)
	at scala.tools.nsc.interactive.Global.signalParseProgress(Global.scala:329)
	at scala.tools.nsc.ast.parser.Parsers$Parser.funDefRest(Parsers.scala:2619)
	at scala.tools.nsc.ast.parser.Parsers$Parser.funDefOrDcl(Parsers.scala:2576)
	at scala.tools.nsc.ast.parser.Parsers$Parser.defOrDcl(Parsers.scala:2461)
	at scala.tools.nsc.ast.parser.Parsers$Parser.nonLocalDefOrDcl(Parsers.scala:2473)
	at scala.tools.nsc.ast.parser.Parsers$Parser$$anonfun$templateStat$1$$anonfun$applyOrElse$3.apply(Parsers.scala:3030)
	at scala.tools.nsc.ast.parser.Parsers$Parser$$anonfun$templateStat$1$$anonfun$applyOrElse$3.apply(Parsers.scala:3030)
	at scala.tools.nsc.ast.parser.Parsers$Parser.joinComment(Parsers.scala:698)
	at scala.tools.nsc.ast.parser.Parsers$Parser$$anonfun$templateStat$1.applyOrElse(Parsers.scala:3030)
	at scala.tools.nsc.ast.parser.Parsers$Parser$$anonfun$templateStat$1.applyOrElse(Parsers.scala:3025)
	at scala.tools.nsc.ast.parser.Parsers$Parser.statSeq(Parsers.scala:2957)
	at scala.tools.nsc.ast.parser.Parsers$Parser.templateStats(Parsers.scala:3024)
	at scala.tools.nsc.ast.parser.Parsers$Parser$$anonfun$templateStatSeq$1.apply(Parsers.scala:3011)
	at scala.tools.nsc.ast.parser.Parsers$Parser$$anonfun$templateStatSeq$1.apply(Parsers.scala:2988)
	at scala.tools.nsc.ast.parser.Parsers$Parser.checkNoEscapingPlaceholders(Parsers.scala:462)
	at scala.tools.nsc.ast.parser.Parsers$Parser.templateStatSeq(Parsers.scala:2988)
	at scala.tools.nsc.ast.parser.Parsers$Parser.templateBody(Parsers.scala:2917)
	at scala.tools.nsc.ast.parser.Parsers$Parser.templateBodyOpt(Parsers.scala:2924)
	at scala.tools.nsc.ast.parser.Parsers$Parser.templateOpt(Parsers.scala:2888)
	at scala.tools.nsc.ast.parser.Parsers$Parser.objectDef(Parsers.scala:2773)
	at scala.tools.nsc.ast.parser.Parsers$Parser.tmplDef(Parsers.scala:2712)
	at scala.tools.nsc.ast.parser.Parsers$Parser.topLevelTmplDef(Parsers.scala:2693)
	at scala.tools.nsc.ast.parser.Parsers$Parser$$anonfun$topStat$1$$anonfun$applyOrElse$2.apply(Parsers.scala:2980)
	at scala.tools.nsc.ast.parser.Parsers$Parser$$anonfun$topStat$1$$anonfun$applyOrElse$2.apply(Parsers.scala:2980)
	at scala.tools.nsc.ast.parser.Parsers$Parser.joinComment(Parsers.scala:698)
	at scala.tools.nsc.ast.parser.Parsers$Parser$$anonfun$topStat$1.applyOrElse(Parsers.scala:2980)
	at scala.tools.nsc.ast.parser.Parsers$Parser$$anonfun$topStat$1.applyOrElse(Parsers.scala:2973)
	at scala.tools.nsc.ast.parser.Parsers$Parser.statSeq(Parsers.scala:2957)
	at scala.tools.nsc.ast.parser.Parsers$Parser.topStatSeq(Parsers.scala:2972)
	at scala.tools.nsc.ast.parser.Parsers$Parser$$anonfun$compilationUnit$1.topstats$1(Parsers.scala:3170)
	at scala.tools.nsc.ast.parser.Parsers$Parser$$anonfun$compilationUnit$1.apply(Parsers.scala:3176)
	at scala.tools.nsc.ast.parser.Parsers$Parser$$anonfun$compilationUnit$1.apply(Parsers.scala:3138)
	at scala.tools.nsc.ast.parser.Parsers$Parser.checkNoEscapingPlaceholders(Parsers.scala:462)
	at scala.tools.nsc.ast.parser.Parsers$Parser.compilationUnit(Parsers.scala:3138)
	at scala.tools.nsc.ast.parser.Parsers$SourceFileParser$$anonfun$parseStartRule$1.apply(Parsers.scala:146)
	at scala.tools.nsc.ast.parser.Parsers$SourceFileParser$$anonfun$parseStartRule$1.apply(Parsers.scala:146)
	at scala.tools.nsc.ast.parser.Parsers$Parser$$anonfun$parse$1.apply(Parsers.scala:352)
	at scala.tools.nsc.ast.parser.Parsers$Parser$$anonfun$parse$1.apply(Parsers.scala:352)
	at scala.tools.nsc.ast.parser.Parsers$Parser.parseRule(Parsers.scala:345)
	at scala.tools.nsc.ast.parser.Parsers$Parser.parse(Parsers.scala:352)
	at scala.tools.nsc.ast.parser.Parsers$UnitParser.smartParse(Parsers.scala:241)
	at scala.tools.nsc.ast.parser.SyntaxAnalyzer.scala$tools$nsc$ast$parser$SyntaxAnalyzer$$initialUnitBody(SyntaxAnalyzer.scala:87)
	at scala.tools.nsc.ast.parser.SyntaxAnalyzer$ParserPhase.apply(SyntaxAnalyzer.scala:99)
	at scala.tools.nsc.Global$GlobalPhase$$anonfun$applyPhase$1.apply$mcV$sp(Global.scala:440)
	at scala.tools.nsc.Global$GlobalPhase.withCurrentUnit(Global.scala:431)
	at scala.tools.nsc.Global$GlobalPhase.applyPhase(Global.scala:440)
	at scala.tools.nsc.Global$Run$$anonfun$compileLate$2$$anonfun$apply$1.apply(Global.scala:1609)
	at scala.tools.nsc.Global$Run$$anonfun$compileLate$2$$anonfun$apply$1.apply(Global.scala:1609)
	at scala.reflect.internal.SymbolTable.enteringPhase(SymbolTable.scala:235)
	at scala.tools.nsc.Global$Run$$anonfun$compileLate$2.apply(Global.scala:1609)
	at scala.tools.nsc.Global$Run$$anonfun$compileLate$2.apply(Global.scala:1608)
	at scala.collection.Iterator$class.foreach(Iterator.scala:742)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1194)
	at scala.tools.nsc.Global$Run.compileLate(Global.scala:1608)
	at scala.tools.nsc.interactive.Global.scala$tools$nsc$interactive$Global$$parseAndEnter(Global.scala:656)
	at scala.tools.nsc.interactive.Global.backgroundCompile(Global.scala:562)
	at scala.tools.nsc.interactive.PresentationCompilerThread.run(PresentationCompilerThread.scala:25)
```

**Comment by edwardsmatt** [comment]
FYI: https://github.com/lihaoyi/Ammonite/issues/257

**Pull request merged**
