### PR TITLE
 Resolution of local Maven artefacts does not work #611

### PR DESCRIPTION
**Pull request by mduerig**
Add resolver for local Maven cache

### CODE REVIEW

**Comment by alexarchambault** [comment]
I wouldn't recommend adding `~/.m2/repository` by default. It sometimes misses artifacts (like it has the POMs but not the JARs), which confuses coursier - if a repo has a POM, coursier expects it to have the JAR too... I could add a helper in coursier (like `coursier.MavenRepository.m2Local`) to make it easier to add it from ammonite though.

**Comment by mduerig** [comment]
`coursier.MavenRepository.m2Local` would be a better solution and nicely inline with `coursier.Cache.ivy2Local`.

**Comment by alexarchambault** [comment]
Possibly even `coursier.Cache.m2Local` :-) Or I wanted to move `ivy2Local` under `coursier.IvyRepository`...

**Comment by lihaoyi** [comment]
@mduerig Regardless of what changes you end up doing to coursier, do you still want to add it by default to Ammonite's resolvers? If not you can always add it manually in your own predef/earlier-block, and I'll close this issue/PR

**Comment by mduerig** [comment]
@lihaoyi , I agree with @alexarchambault that this is better tackled in one way or another in coursier. Once this is done we can get back to this issue and see how to fix it. In the meanwhile let's close the PR.

**Comment by lihaoyi** [comment]
sgtm

**Pull request closed without merging**
