### PR TITLE
Allow to interrupt user code via Ctrl-C again

### PR DESCRIPTION
**Pull request by alexarchambault**
Fixes https://github.com/lihaoyi/Ammonite/issues/920.

### CODE REVIEW

**Comment by lihaoyi** [comment]
no idea but ok

**Comment by lihaoyi** [comment]
👍

**Comment by alexarchambault** [comment]
@lihaoyi This is not a perfect fix. Now when one type Ctrl-C after having entered some code, without pressing enter, nothing happens.

**Comment by alexarchambault** [comment]
Previously, the current line was left in the terminal, and a new cursor was printed below.

**Comment by alexarchambault** [comment]
I'd like to have it behave like before too… Do you know what code is handling the Ctrl-C when accepting input? The `Signaller` in the second commit here should call it somehow. I guess it must be around `AmmoniteFrontEnd`, but I can't find it…

**Comment by lihaoyi** [comment]
@alexarchambault not sure, might have been this guy? https://github.com/lihaoyi/Ammonite/blob/1.2.0/terminal/src/main/scala/ammonite/terminal/filters/BasicFilters.scala#L92

**Comment by alexarchambault** [comment]
So the new commit restores a bit the behavior prior to https://github.com/lihaoyi/Ammonite/pull/853. But this runs commands before / after reading input, which slows down things a bit (like before https://github.com/lihaoyi/Ammonite/pull/853, but most of its other gains should still be there).

Ideally, a `Signaller("INT")` could be added around the call to initial call to `loop()` in `ammonite.repl.Repl`. The handler could then manage to tell the `LineReader` to do as if it received a Ctrl-C. When the Ctrl-C arrives, the `LineReader` is just reading input, so it should be interrupted somehow, or the Ctrl-C could be manually injected in its input stream…

**Comment by alexarchambault** [comment]
Superseded by https://github.com/lihaoyi/Ammonite/pull/923.

**Pull request closed without merging**
