### PR TITLE
Remove "Main.scala: xx" from compilation failure reports in repl

### PR DESCRIPTION
**Pull request by lastland**
The "Main.scala: xx" from the compilation failure reports do not help diagnose the problem. Further, it could cause confusion to beginners.

For example, the following code:

    @ a.foreach(println(_))

will result in:

    Compilation Failed
    Main.scala:33: not found: value a
    a.foreach(println(_))
    ^

This PR changes it to:

    Compilation Failed
    not found: value a
    a.foreach(println(_))
    ^

### CODE REVIEW

**Comment by lihaoyi** [comment]
Will loo at it when i get back from work, thanks!

**Comment by lihaoyi** [comment]
What if the output has multiple lines, and one of it has a non-`Main.scala` colon `:` in it? Won't this incorrectly chop it off in such a case?

**Comment by lastland** [comment]
You are right. Thanks for pointing it out!

I've made some updates on the code, together with a corresponding test case.

**Comment by lihaoyi** [comment]
Sorry for the long delay! Was busy at work -.-

This doesn't seem to behave properly with multiple lines with errors

```scala
haoyi-Ammonite@ {
                asd
                ads
                }
Compilation Failed
not found: value asd
asd
^
Main.scala:124: not found: value ads
ads
^
```

I'm honestly doubtful that this string-splicing approach to removing this is going to work and be robust overall, even by Ammonite's low standards =/ e.g. we can't just regex Main.scala because that may be part of the legitimate output if the line with an error starts with the tail end of a triple-quoted string. Perhaps some kind of compiler plugin that intercepts these errors before they get stringified would be more successful.

**Comment by lastland** [comment]
No worries :smile: 

Yeah you make a very good point here. However, do you thinking renaming "Main.scala" to some special name that would be unlikely to appear (for example, `__Main__.scala`?) would be a possible solution?

**Pull request closed without merging**
