### PR TITLE
Infix type printing now shows grouping

### PR DESCRIPTION
**Pull request by ulasakdeniz**
Fixes: #319 
Thought that was an easy one, not sure if it's a correct solution though 😄

### CODE REVIEW

**Comment by lihaoyi** [comment]
Yeah this is probably the wrong solution. We want the infix operations, but we want parens around them (only where necessary!) to maintain the correct infix order of nesting.

**Comment by ulasakdeniz** [comment]
If you give me more detail I can work on it.

**Comment by lihaoyi** [comment]
The original test case still applies
```scala
naftoli-platinum@ trait *[A, B]
defined trait *
naftoli-platinum@ trait +[A, B]
defined trait +
naftoli-platinum@ null: (Int + Int * Int)
res2: Int + Int * Int = null
naftoli-platinum@ null: (Int + (Int * Int))
res3: Int + Int * Int = null
naftoli-platinum@ null: ((Int + Int) * Int)
res4: Int + Int * Int = null
```

`(Int + (Int * Int))` and `((Int + Int) * Int)` both are rendered as `Int + Int * Int`, but are different types. Ideally the second case would render as `(Int + Int) * Int`

**Comment by ulasakdeniz** [comment]
I thought that it should give output like Scala REPL, I can take a look at it when I'm available, thanks.

**Pull request closed without merging**
