### PR TITLE
Update coursier to 1.0.0

### PR DESCRIPTION
**Pull request by piotrkwiecinski**
Latest stable release or coursier

### CODE REVIEW

**Comment by alexarchambault** [comment]
@piotrkwiecinski Note that [this line](https://github.com/lihaoyi/Ammonite/blob/master/project/plugins.sbt#L14) can now be removed (thanks to https://github.com/coursier/coursier/pull/712).

**Comment by lihaoyi** [comment]
Thanks!

**Comment by emanresusername** [comment]
@lihaoyi @alexarchambault any idea why [this test fails](https://github.com/lihaoyi/Ammonite/pull/713/files#diff-ba4b71b2d310a9c84efade59dff114d4R331) on `RC9` and up? or can anybody reproduce or is something just wrong with my computers? (tried on two)
is there some cached config somewhere (aside from `~/{.ivy2,.sbt,.coursier}` that might be interfering (blew all those away and it still breaks for me) 😭

**Comment by alexarchambault** [comment]
@emanresusername I think that originates from the "optional" artifacts, that were added in some RCs of coursier. Namely, one should get the artifacts via [the method accepting an extra arg](https://github.com/coursier/coursier/blob/b21042a42a6b2718ec1116f28f76dd769112c6aa/core/shared/src/main/scala/coursier/core/Resolution.scala#L1048), passing it `true`, then ignore not found errors for artifacts that are [optional](https://github.com/coursier/coursier/blob/b21042a42a6b2718ec1116f28f76dd769112c6aa/core/shared/src/main/scala/coursier/core/Definitions.scala#L206) (but not ignoring the other kinds of errors).

That way, optional artifacts would be loaded in ammonite, and that test case should be fine.

**Pull request merged**
