### PR TITLE
Document how current working directoy works in ammonite

### PR DESCRIPTION
**Pull request by cvogt**

### CODE REVIEW

**Comment by lihaoyi** [comment]
Looks great, thanks! I'll write more about it later

**Comment by cvogt** [comment]
FYI, I didn't compile this. Also I found a small typo "or" instead of "of".

**Comment by lihaoyi** [comment]
That's ok. Travis compiles it every time!

**Comment by cvogt** [comment]
I figured you had CI running, but didn't see the big green box, but now I see the little green check mark now. Cool :).

**Pull request merged**
