### PR TITLE
History search

### PR DESCRIPTION
**Pull request by lihaoyi**
Re-implementation of https://github.com/lihaoyi/Ammonite/pull/281, but better

- Searches contents, not just prefixes
- Underlines things which are being searched for, making it relatively clear (?) when a search is taking place and when it isn't
- Relatively intuitive (?) behavior around starting, ending, and navigating through the search history. In particular:
  - It supports both `UP` and `Ctrl-R` as ways to start a search
  - Printable characters or backspaces modify the search in place, and narrow it in the case of additional characters.
  - Any control character ends the search and forwards to the default behavior; e.g. `ENTER` ends the search and executes the command, `LEFT`/`RIGHT` end the search and move the cursor, etc.
- Only uses two `var`s instead of seven

Misc changes 
- Upgrade pprint to allow nicely format config files
- disable travis cache because it's misbehaving =/

### CODE REVIEW

**Comment by lihaoyi** [comment]
@olafurpg want to give this a whirl and let me know what you think?

**Comment by olafurpg** [comment]
Absolutely! However, I'm traveling without my laptop until tomorrow evening so I can't provide feedback before then.

**Comment by lihaoyi** [comment]
Tomorrow is fine =)

**Comment by olafurpg** [comment]
First of all, amazing work. I can't wait to get this :smile_cat: 

> Searches contents, not just prefixes

Being used to oh-my-zsh, it's a bit unusual at first. However, it became natural quickly. 

> Underlines things which are being searched for, making it relatively clear (?) when a search is taking place and when it isn't.

I think it's intuitive. Pressing right/left to exit the search is perfect.

> Relatively intuitive (?) behavior around starting, ending, and navigating through the search history.

Nitpick, consider
```
@ 123
res16: Int = 123
@ 123<UP> ...cannot be found in the history
```
123 is in history. Maybe, the message should rather be "...reached top of history."?

```
@ 123
res16: Int = 123
@ 12<UP,UP,UP,...>
```
cycles between 12 and 123 with no hint that you're cycling the history (with a longer history it might not be so obvious). Maybe use the same "...reached top of history." message when you reach 123?

Finally, I would argue that #297 still needs a bit work. Consider:

```
@ val s = "hello"
s: String = "hello"
@ <UP>val s = "hello"<s/hello"/goodbye"/><DOWN><UP><ENTER>
s: String = "hello"
```
I would expect after the `<DOWN><UP>` that my edit from hello to goodbye would be preserved. It's a shame to lose an edit because I accidentally pressed down (happens a lot while editing multiline strings!).

**Comment by lihaoyi** [comment]
> 123 is in history. Maybe, the message should rather be "...reached top of history."?

Yeah, or it should just scroll around,

>  I would expect after the <DOWN><UP> that my edit from hello to goodbye would be preserved. It's a shame to lose an edit because I accidentally pressed down (happens a lot while editing multiline strings!).

Eh? I thought it would keep the thing after making edits, but it clearly doesn't. That's a bug. My expected behavior is that after editing the text, you wouldn't be able to go `<DOWN>`  anymore

**Comment by olafurpg** [comment]
> My expected behavior is that after editing the text, you wouldn't be able to go <DOWN> anymore.

The bug happens when I press up *without* a search term. If I have a search term it works as intended.

Also, in b6ef733ab2c67301e27a8061448f834fb214a753:

* left/right doesn't exit from search anymore.
*  From an empty command `<ctrl-r><enter>` gives me

```
@  ...enter the string to search, then `up` for more results
SyntaxError: found "\u001b[34m...enter the st", expected TopPkgSeq | Import | Prelude ~ BlockDef | Expr | End at index 1
```

**Comment by lihaoyi** [comment]
> left/right doesn't exit from search anymore.

Hmm yeah. The original idea was that you when browsing history without a search term, you should be able to navigate around before making an edit to drop out. The behavior should differ between "empty history browsing" and "searching for term"

> From an empty command <ctrl-r><enter> gives me

I don't see this... it's definitely a bug and i'll fix it if I can repro

**Pull request merged**
