### PR TITLE
Fix --bsp

### PR DESCRIPTION
**Pull request by alexarchambault**
Regression from https://github.com/lihaoyi/Ammonite/pull/1144, reported in https://github.com/lihaoyi/Ammonite/commit/959a05334361428e77c853415bcbe4fed11ec330#r46029299.

### CODE REVIEW

**Review by tgodzik — APPROVED** [review]
Thanks a lot for the fix!

**Comment by tgodzik** [comment]
@alexarchambault would it be possible to release a new version with the fix?

**Comment by alexarchambault** [comment]
My bad, I thought the CI release jobs would have passed since then :|

It seems I can't re-run GitHub actions jobs, maybe because they're too old now. I just merged https://github.com/lihaoyi/Ammonite/pull/1143, hoping it'll work this time.

**Comment by alexarchambault** [comment]
Ok, it failed again (timeout from mill), but I was able to manually release stuff from the Sonatype UI. Just waiting for the sync to Central now.

**Comment by tgodzik** [comment]
Awesome! Thanks!

**Comment by tgodzik** [comment]
Trying it out here https://github.com/scalameta/metals/pull/2530/files !

**Pull request merged**
